/*
# Create ALSALE approval requests

1. New Tables
- `approval_requests` stores payment voucher and memorandum requests in the shared ALSALE workspace.
- `id` identifies each request.
- `request_number` stores the human-friendly ALS reference.
- `request_type` distinguishes payment vouchers from memoranda.
- `title`, `description`, `amount`, and `currency` capture the request details.
- `requester`, `department`, `recipient`, and `from_party` capture the memo routing information.
- `urgency` captures normal, urgent, or emergency handling.
- `status` captures pending, approved, rejected, or paid progress.
- `created_at` and `updated_at` track the request timeline.

2. Security
- Row level security is enabled.
- This is intentionally a single-tenant internal workspace without sign-in in the first release, so anon and authenticated users can manage shared records.
- Separate CRUD policies are created for the anon and authenticated roles.

3. Notes
- No existing tables are modified.
- The request number is generated by the application so the dashboard can display readable references.
*/

CREATE TABLE IF NOT EXISTS public.approval_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_number text NOT NULL UNIQUE,
  request_type text NOT NULL CHECK (request_type IN ('payment_voucher', 'memorandum')),
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
  currency text NOT NULL DEFAULT 'GHC',
  requester text NOT NULL,
  department text NOT NULL DEFAULT 'General Management',
  recipient text NOT NULL DEFAULT '',
  from_party text NOT NULL DEFAULT '',
  urgency text NOT NULL DEFAULT 'normal' CHECK (urgency IN ('normal', 'urgent', 'emergency')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'paid')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.approval_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "shared_select_approval_requests" ON public.approval_requests;
CREATE POLICY "shared_select_approval_requests" ON public.approval_requests
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "shared_insert_approval_requests" ON public.approval_requests;
CREATE POLICY "shared_insert_approval_requests" ON public.approval_requests
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "shared_update_approval_requests" ON public.approval_requests;
CREATE POLICY "shared_update_approval_requests" ON public.approval_requests
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "shared_delete_approval_requests" ON public.approval_requests;
CREATE POLICY "shared_delete_approval_requests" ON public.approval_requests
  FOR DELETE TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS approval_requests_status_idx ON public.approval_requests(status);
CREATE INDEX IF NOT EXISTS approval_requests_created_at_idx ON public.approval_requests(created_at DESC);
